language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r garageon-webservice *
  - mkdir -p deploy
  - mv garageon-webservice.zip deploy/garageon-webservice.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo settings에 설정된 값
    bucket: garageon-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: garageon-build
    key: garageon-webservice.zip

    bundle_type: zip
    application: garageon-webservice

    deployment_group: garageon-webservice-group

    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행완료시 메일로 알림
notifications:
  email:
    recipients:
      - Yeolo03@naver.com